version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
